In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
from sklearn.lda import LDA
from sklearn.metrics import confusion_matrix
from __future__ import division
%matplotlib inline

In [69]:
smarkets = pd.read_csv('data/Smarket.csv')
smarkets.head()

Year   Lag1   Lag2   Lag3   Lag4   Lag5  Volume  Today Direction
0  2001  0.381 -0.192 -2.624 -1.055  5.010  1.1913  0.959        Up
1  2001  0.959  0.381 -0.192 -2.624 -1.055  1.2965  1.032        Up
2  2001  1.032  0.959  0.381 -0.192 -2.624  1.4112 -0.623      Down
3  2001 -0.623  1.032  0.959  0.381 -0.192  1.2760  0.614        Up
4  2001  0.614 -0.623  1.032  0.959  0.381  1.2057  0.213        Up

In [70]:
# Train the model

smarkets_train = smarkets[smarkets.Year<2005]
X = np.array(smarkets_train[['Lag1','Lag2']])
#convert strings "Up" and "Down" to 1 and 0.
cat_var = {'Up':1,'Down':0}
y = np.array([cat_var[x] for x in smarkets_train.Direction])
clf = LDA() # clf is the name that skilearn gives it (not sure why)
clf.fit(X,y)

LDA(n_components=None, priors=None, shrinkage=None, solver='svd',
  store_covariance=False, tol=0.0001)

In [71]:
# Test the model

smarkets_test = smarkets[smarkets.Year>=2005]
X_test = np.array(smarkets_test[['Lag1','Lag2']])
y_test = np.array([cat_var[x] for x in smarkets_test.Direction])
pred = clf.predict(X_test)
sum(y_test == pred)/len(smarkets_test)


0.55952380952380953

In [72]:
# confusion matrix
correct = y_test == pred
TP = sum(pred[correct] == 0)
FP = sum(pred[-correct] == 0)
TN = sum(pred[correct] == 1)
FN = sum(pred[-correct] == 1)
print np.array([[TP,FN],[FP,TN]])
print FN
confusion_matrix(y_test,pred)

[[ 35  76]
 [ 35 106]]
76


array([[ 35,  76],
       [ 35, 106]])

In [60]:
print y_test[0:4]
print pred[0:4]

[0 0 0 1]
[1 1 1 1]


In [62]:
confusion_matrix(y_test[0:4],pred[0:4])

array([[0, 3],
       [0, 1]])

In [65]:
correct

array([False, False, False,  True], dtype=bool)

In [67]:
y_test[-correct]

array([0, 0, 0])